### ISSUE TITLE
Value "auto auto" not permitted in tts:extent in TTML1.

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2-tests#136]
The test `/validation/valid/ttml2-valid-extent-1-region.xml` uses values like `auto auto` which are not permitted in TTML1.

**Comment by nigelmegitt** [comment]
Why is this an issue @spoeschel ? This is the TTML2 tests repo...

**Comment by spoeschel** [comment]
My assumption was that this test covers the TTML1 subset of tts:extent that is contained in TTML2 and hence was intended to comply to TTML1. So this is not the intention here?

**Comment by nigelmegitt** [comment]
Indeed it is not the intention - these tests are specifically for testing the new features introduced in  TTML2, so it is exactly the opposite! Can you close if there's no other issue please, @spoeschel ?

**Comment by spoeschel** [comment]
Ah OK, I see. Thanks for the explanation. So I close here.

**Comment by skynavga** [comment]
Actually, @spoeschel is correct. This test was intended to test only TTML1 values (as indicated in the comment in the spec).

**Comment by skynavga** [comment]
@nigelmegitt some of the new TTML2 feature designators include TTML1 values, and in some of these (not all), I have added (validation related) tests for some subset of the TTML1 values

**Comment by nigelmegitt** [comment]
@skynavga So this is for the [`#extent-region`](https://www.w3.org/TR/ttml2/#feature-extent-region) feature? If that is the case, then my understanding is that the feature does not need to be tested in the implementation report test suite; it is excluded by the "For each feature introduced in this specification" wording in the CR exit criteria part of the SoTD.

**Comment by nigelmegitt** [comment]
@skynavga I see `#extent-region` in TTML1 at https://www.w3.org/TR/ttml1/#feature-extent-region and just to check we didn't introduce it in 3rd Ed (we didn't introduce any feature designators in TTML1 3rd Ed but I wanted to double check): https://www.w3.org/TR/2013/REC-ttml1-20130924/#feature-extent-region too.
