### ISSUE TITLE
Data element does not conform to model at ttml2-valid-resources-all.xml.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2-tests#141]
The `data` element at `ttml2-valid-resources-all.xml` conforms to neither simple data embedding, chunked data embedding, nor sourced data embedding model.

**Comment by skynavga** [comment]
And yet, it remains valid; otherwise, the presence of @src is redundant. The spec just doesn't give this usage a convenient name (yet), something we can do in 2e. I will move these into a new pending directory.

**Comment by skynavga** [comment]
See https://github.com/w3c/ttml2/issues/986.
