### ISSUE TITLE
ttml2-invld-image-embedding-bad-resource.xml does not appear invalid

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2-tests#142]
As in https://github.com/w3c/ttml2-tests/issues/132 , the specification does not impose a requirement on when or whether the `src` URI is resolvable.

**Comment by palemieux** [comment]
Same for all `ttml2-invld-image-in-*` tests

**Comment by skynavga** [comment]
The source is resolvable; however, it content does not adhere to the PNG specification. Reporting an invalidity is based on the following language in 9.1.5. In this test, the type of the specified resource does not correspond with the specified type.

>If an image element specifies a src attribute and its value does not refer to a fragment of the enclosing document instance, then it should specify a type attribute, in which case the value of the type attribute must correspond with the media (content) type of the referenced resource.

**Comment by palemieux** [comment]
> As for what validators are compelled to implement, please keep in mind that we do not require any validator to detect any invalidity. 

That does not work since a null validator would pass all tests.

> The detection of invalidities in a validator is a QOI issue, and not a compliance issue.

I think you are trying to say that validation of image format is a good test, but not one required for the implementation report/exit criteria. If so, I agree.

**Comment by skynavga** [comment]
Yes, as we have defined validation, a null validator will pass all tests. None of the invalid tests are required to be used for the IR exit criteria. I have elsewhere stated that a validator passes if it does not produce a false negative for the valid tests (only). It is not required that a validator NOT produce a false positive result for any invalidity test.
