### ISSUE TITLE
Region elements missing @xml:id.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2-tests#148]
TTML 2 states that _an out-of-line region element must specify an xml:id attribute_

Multiple tests are missing `@xml:id` on `region` elements, e.g. `ttml2-valid-extent-2-region-contain.xml`

**Comment by skynavga** [comment]
Hmm, that slipped through without notice. It potentially invalidates TTML1 content which did not have this constraint. We will need to back this out in 2e.

**Comment by skynavga** [comment]
See https://github.com/w3c/ttml2/issues/989.

**Comment by palemieux** [comment]
Can the tests be fixed by adding xml:id is the meantime?
