### ISSUE TITLE
ttml2-invld-processor-profiles-designator-delimiter-syntax.xml is a valid document

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2-tests#154]
`http://www.w3.org/ns/ttml/profile/ttml2-transformation,` is a valid URI

**Comment by skynavga** [comment]
the invalidity is on

`ttp:processorProfiles="http://www.w3.org/ns/ttml/profile/ttml2-transformation, http://www.w3.org/ns/ttml/profile/ttml2-transformation"`

see also the XML comment at the top of the file:

`<!-- invalid - processor profiles parameter with bad designator delimiter - comma -->`

**Comment by palemieux** [comment]
`http://www.w3.org/ns/ttml/profile/ttml2-transformation,` is a valid URI, so the list of profiles consists of:

* `http://www.w3.org/ns/ttml/profile/ttml2-transformation,`
* `http://www.w3.org/ns/ttml/profile/ttml2-transformation`

**Comment by skynavga** [comment]
Fixed in a80fc4dcc7bf26693b19cf629bd06af31bc2caa0. Use whitespace separated COLON as delimiter.
