### ISSUE TITLE
ttml2-invld-xlink-href-empty.xml is not invalid

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2-tests#155]
`xlink:href` permits relative URIs, which include the empty URI.

**Comment by skynavga** [comment]
I disagree. I would also note that the XML Schema data type xsd:anyURI does not include the empty string in its set of lexical representations. Note that RFC2396 has:

```
relativeURI   = ( net_path | abs_path | rel_path ) [ "?" query ]
rel_segment   = 1*( unreserved | escaped | ";" | "@" | "&" | "=" | "+" | "$" | "," )
```

which means that a relative URI must contain at least one character that matches rel_segment (if it is not a net_path or abs_path, both of which start with one or two '/' characters.

**Comment by palemieux** [comment]
From [xlink 1.1](https://www.w3.org/TR/2010/REC-xlink11-20100506/#link-locators)

_If the value of the href attribute is a relative reference_

and from [RFC 3986](https://tools.ietf.org/html/rfc3986):

```
relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

      relative-part = "//" authority path-abempty
                    / path-absolute
                    / path-noscheme
                    / path-empty
```

**Comment by palemieux** [comment]
Ah. xsd:anyURI is tied to https://www.ietf.org/rfc/rfc2396.txt . The latter in Section 4.2 states:

```
A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.
```

**Comment by skynavga** [comment]
Mark test as excluded from exit criteria (89a052951bec3ca0f083add96814ae4b2b940c0f). Sort out possible spec changes in 2e.
