### ISSUE TITLE
tts:writingMode not significant

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2-tests#156]
https://github.com/w3c/ttml2-tests/blob/89a052951bec3ca0f083add96814ae4b2b940c0f/validation/valid/ttml2-valid-set.xml#L17

The attribute `tts:writingMode` is not significant on `div` (or a `set` child of it, as here) and also cannot be inherited by an element on which it would be significant (`region`).

**Comment by skynavga** [comment]
Addressed in 1e4f770dbb64a7ede17af792fdc5efe6bf1f4eb6.
