### ISSUE TITLE
Missing alpha color component

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2-tests#157]
https://github.com/w3c/ttml2-tests/blob/89a052951bec3ca0f083add96814ae4b2b940c0f/validation/invalid/ttml2-invld-bad-background-color-space-padded-rgba-function.xml#L9

Assuming that it is not the intention to test the color function itself here, the alpha component is missing.

**Comment by skynavga** [comment]
Addressed in 1e4f770dbb64a7ede17af792fdc5efe6bf1f4eb6.
