### ISSUE TITLE
validation/tests.json: small issues

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2-tests#158]
Some test cases are listed in the wrong valid/invalid group:
- ttml2-valid-initial-duplicate
- ttml2-invld-bad-set-unknown-repeat-count

Some test names are misspelled:
- ttml2-vaoid-background-color-rgb-function-padded-component
- ttml2-vaoid-background-color-rgba-function-padded-component

**Comment by skynavga** [comment]
Addressed in 1e4f770dbb64a7ede17af792fdc5efe6bf1f4eb6.
