### ISSUE TITLE
Embedded audio gives base64 decode error.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2-tests#185]
When base64 decoding the audio in:

* `ttml2-prstn-audio-embedding-chunked.xml` and 
* `ttml2-prstn-audio-embedding-sourced.xml` 

there's an invalid character error (input to base64 formed by creating a text file from the source data):

```
$ base64 -D -i chunked-source-base64.txt -o chunked-source-audio.wav
Invalid character in input stream.
```

I will propose a pull request that replaces the base64 encoded data with audio data that does not produce this error.

**Comment by skynavga** [comment]
Actually, it was my intention to permit normal XML whitespace characters in base64 data, which is permitted [1], and which would be ignored by decoders [2]. However, I see that RFC4648 wants the referring spec (in our case TTML2) to explicitly sanction such usage. I will add an issue (for resolution in 2e) to explicitly permit these characters within base64 data.

[1] https://tools.ietf.org/html/rfc4648#section-3.3
[2] https://tools.ietf.org/html/rfc4648#section-3.3
