### ISSUE TITLE
Add embedded font family test.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2-tests#201]
See https://github.com/w3c/ttml2/pull/1049#issuecomment-476124720.

**Comment by nigelmegitt** [comment]
The added test checks only for validation of invalid font family names. Still to do: 

* [ ] validation of valid font family names that differ from generic names only by change of case;
* [ ] presentation of text whose `tts:fontFamily` computed value is a generic family name and a font is defined with the same generic family name in the `family` attribute - the output must use the default font not the included/referenced font.

**Comment by skynavga** [comment]
While we can add as many tests as we like, you asked for a test, and the merged PR adds such a test. There is no requirement that says what must be tested or defines _completeness_ with regard to testing. I'm certain that for every test that exists in the TS, you can think of _N_ more tests to add (no matter how large you want to make _N_). If you want to add more tests, then open new issues along with PRs that satisfy them. In the mean time, I am re-closing this issue.

**Comment by nigelmegitt** [comment]
I don't agree with @skynavga 's summary from 26 March. This is the generic ticket to add font family tests associated with the normative specification changes in TTML2 from w3c/ttml2#1049. That change introduced 3 individually testable things, and it's my position that we should test all of them:

1. generic font family names in font elements are considered an error.
2. comparison of font family names with generic font family names is case sensitive.
3. referenced font resources where the font family name matches a generic font family name must be ignored for presentation.

We have tested only the first one therefore we have not completed this issue.

**Comment by skynavga** [comment]
Moving follow-on work from  https://github.com/w3c/ttml2-tests/issues/201#issuecomment-594479656 to #254 and re-closing this issue.
