### ISSUE TITLE
Add ruby tests.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2-tests#240]
Add tests to support w3c/ttml2#1077.

**Comment by skynavga** [comment]
On a validating processor, the appearance of LWSP in ruby container, ruby base container or ruby text container context must produce an invalidity error (unless disabled). On a non-validating processor, however, such LWSP must be ignored regardless of whether `xml:space` is `preserve` or not. Therefore, the only way to test the latter is specify ``xml:space='preserve'``, disable validation, then check if LWSP is ignored.

**Comment by nigelmegitt** [comment]
Additionally, the PR introduced normative language for what a presentation processor must do in the presence of LWSP in those ruby elements, which is to ignore them. Therefore we should have presentation test(s) where the input document includes LWSP and the presented output is the same as if that LWSP had been absent.

**Comment by skynavga** [comment]
I need to refine my comment https://github.com/w3c/ttml2-tests/issues/240#issuecomment-593150390 above; in particular, the presence of LWSP, more particularly, [`<lwsp>`](https://w3c.github.io/ttml2/index.html#style-value-lwsp), does not produce an invalidity error, and, indeed, is the only permissible non-markup content that may appear in a ruby container, ruby base container, or ruby text container. If, however, the `xml:space` in effect is `preserve`, then that LWSP is nevertheless to be ignored for presentation purposes. That means that, for validation purposes, there is no testable impact for this issue w.r.t. the presence or absence of LWSP in a ruby container context. The only potential test is that suggested by @nigelmegitt in https://github.com/w3c/ttml2-tests/issues/240#issuecomment-594482063.
