### ISSUE TITLE
Add #extent-root-version-2 tests.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2-tests#246]
Add tests to support w3c/ttml2#1110.

**Comment by skynavga** [comment]
This change does not add a new feature designation, but rather changes an existing aggregate (compound) feature designation to substitute a different referenced component feature designation. This change is not reliably testable due since requiring support for the new definition of `#extent-root-version-2` can be tested by requiring support for `#extent-contain`; however, such support may be present independently from the former which may produce a false positive absent of further evidence. The problem is there is no way to determine if support for `#extent-contain` is present that only derives from support from `#extent-root-version-2`. As such, we should mark the linked PR as untestable and close this issue.

**Comment by nigelmegitt** [comment]
I'm willing to mark this as untestable.
